In [1]:
import pandas as pd
import numpy as np

In [2]:
try:
    locn=pd.read_csv('locations.csv')
    vd=pd.read_csv('make_details.csv')
    sv=pd.read_csv('stolen_vehicles.csv')
except FileNotFoundError as e:
    print(f'Error: {e}')

In [3]:
locn.head(5)

   location_id         region      country population  density
0          101      Northland  New Zealand    201,500    16.11
1          102       Auckland  New Zealand  1,695,200   343.09
2          103        Waikato  New Zealand    513,800    21.50
3          104  Bay of Plenty  New Zealand    347,700    28.80
4          105       Gisborne  New Zealand     52,100     6.21

In [4]:
locn.shape

(16, 5)

In [5]:
locn.isnull().sum()

location_id    0
region         0
country        0
population     0
density        0
dtype: int64

In [6]:
locn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   location_id  16 non-null     int64
 1   region       16 non-null     object
 2   country      16 non-null     object
 3   population   16 non-null     object
 4   density      16 non-null     float64
dtypes: float64(1), int64(1), object(3)
memory usage: 772.0+ bytes

In [7]:
locn['population'] = locn['population'].str.replace(',', '')
locn['population'] = locn['population'].astype(int)

locn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   location_id  16 non-null     int64
 1   region       16 non-null     object
 2   country      16 non-null     object
 3   population   16 non-null     int64
 4   density      16 non-null     float64
dtypes: float64(1), int64(2), object(2)
memory usage: 772.0+ bytes

In [8]:
locn.head(5)

   location_id         region      country  population  density
0          101      Northland  New Zealand      201500    16.11
1          102       Auckland  New Zealand     1695200   343.09
2          103        Waikato  New Zealand      513800    21.50
3          104  Bay of Plenty  New Zealand      347700    28.80
4          105       Gisborne  New Zealand       52100     6.21

In [9]:
locn.duplicated().sum()

np.int64(0)

In [10]:
col=locn.select_dtypes(include='object').columns.tolist()
for i in col:
    print(f"Column: {i}")
    print(locn[i].value_counts(dropna=False))
    print('----------------------------------')

Column: region
region
Northland             1
Auckland              1
Waikato               1
Bay of Plenty         1
Gisborne              1
Hawke's Bay           1
Taranaki              1
Manawatū-Whanganui    1
Wellington            1
Tasman                1
Nelson                1
Marlborough           1
West Coast            1
Canterbury            1
Otago                 1
Southland             1
Name: count, dtype: int64
----------------------------------
Column: country
country
New Zealand    16
Name: count, dtype: int64
----------------------------------

In [11]:
locn['region']=locn['region'].str.replace('Manawatū-Whanganui','Manawatu-Whanganui')
locn

    location_id              region      country  population  density
0           101           Northland  New Zealand      201500    16.11
1           102            Auckland  New Zealand     1695200   343.09
2           103             Waikato  New Zealand      513800    21.50
3           104       Bay of Plenty  New Zealand      347700    28.80
4           105            Gisborne  New Zealand       52100     6.21
5           106         Hawke's Bay  New Zealand      182700    12.92
6           107            Taranaki  New Zealand      127300    17.55
7           108  Manawatu-Whanganui  New Zealand      258200    11.62
8           109          Wellington  New Zealand      543500    67.52
9           110              Tasman  New Zealand       58700     6.10
10          111              Nelson  New Zealand       54500   129.15
11          112         Marlborough  New Zealand       51900     4.94
12          113          West Coast  New Zealand       32700     1.41
13          114          Canterbury  New Zealand      655000    14.72
14          115               Otago  New Zealand      246000     7.89
15          116           Southland  New Zealand      102400     3.28

In [12]:
vd.head(5)

   make_id      make_name make_type
0      501  Aakron Xpress  Standard
1      502           ADLY  Standard
2      503          Alpha  Standard
3      504          Anglo  Standard
4      505        Aprilia  Standard

In [13]:
vd.shape

(138, 3)

In [14]:
vd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 138 entries, 0 to 137
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   make_id    138 non-null    int64
 1   make_name  138 non-null    object
 2   make_type  138 non-null    object
dtypes: int64(1), object(2)
memory usage: 3.4+ KB

In [15]:
vd.duplicated().sum()

np.int64(0)

In [16]:
vd['make_name']=vd['make_name'].str.title()
vd

     make_id      make_name make_type
0        501  Aakron Xpress  Standard
1        502           Adly  Standard
2        503          Alpha  Standard
3        504          Anglo  Standard
4        505        Aprilia  Standard
..       ...            ...       ...
133      634          Volvo    Luxury
134      635        Voyager  Standard
135      636         Yamaha  Standard
136      637         Zephyr  Standard
137      638           Znen  Standard

[138 rows x 3 columns]

In [17]:
col=vd.select_dtypes(include='object').columns.tolist()
for i in col:
    print(f"Column: {i}")
    print(vd[i].value_counts(dropna=False))
    print('----------------------------------')

Column: make_name
make_name
Aakron Xpress    1
Adly             1
Alpha            1
Anglo            1
Aprilia          1
                ..
Volvo            1
Voyager          1
Yamaha           1
Zephyr           1
Znen             1
Name: count, Length: 138, dtype: int64
----------------------------------
Column: make_type
make_type
Standard    123
Luxury       15
Name: count, dtype: int64
----------------------------------

In [18]:
sv.head(5)

,vehicle_id,vehicle_type,make_id,model_year,vehicle_desc,color,date_stolen,location_id
0,1,Trailer,623.0,2021.0,BST2021D,Silver,11-05-2021,102
1,2,Boat Trailer,623.0,2021.0,OUTBACK BOATS FT470,Silver,12/13/21,105
2,3,Boat Trailer,623.0,2021.0,ASD JETSKI,Silver,2/13/22,102
3,4,Trailer,623.0,2021.0,MSC 7X4,Silver,11/13/21,106
4,5,Trailer,623.0,2018.0,D-MAX 8X5,Silver,01-10-2022,102

In [19]:
sv.shape

(4553, 8)

In [20]:
sv[sv.duplicated(keep=False)]

Empty DataFrame
Columns: [vehicle_id, vehicle_type, make_id, model_year, vehicle_desc, color, date_stolen, location_id]
Index: []

In [21]:
sv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4553 entries, 0 to 4552
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   vehicle_id    4553 non-null   int64
 1   vehicle_type  4527 non-null   object
 2   make_id       4538 non-null   float64
 3   model_year    4538 non-null   float64
 4   vehicle_desc  4520 non-null   object
 5   color         4538 non-null   object
 6   date_stolen   4553 non-null   object
 7   location_id   4553 non-null   int64
dtypes: float64(2), int64(2), object(4)
memory usage: 284.7+ KB

In [22]:
sv.isnull().sum()

vehicle_id       0
vehicle_type    26
make_id         15
model_year      15
vehicle_desc    33
color           15
date_stolen      0
location_id      0
dtype: int64

In [23]:
sv[sv['vehicle_type'].isna()]

,vehicle_id,vehicle_type,make_id,model_year,vehicle_desc,color,date_stolen,location_id
4527,4528,NaN,505.0,2017.0,ETX 150,Black,12/13/21,104
4528,4529,NaN,507.0,2011.0,A8,Grey,12/14/21,102
4529,4530,NaN,512.0,2009.0,335i,Black,2/22/22,102
4530,4531,NaN,550.0,2009.0,TTR125,Blue,1/14/22,104
4531,4532,NaN,589.0,2021.0,NQI,whiTe,03-07-2022,102
4532,4533,NaN,611.0,2014.0,SWIFT,Red,11/17/21,108
4533,4534,NaN,611.0,2007.0,JIMNY,Black,01-11-2022,115
4534,4535,NaN,520.0,2005.0,30600,Yellow,11/23/21,102
4535,4536,NaN,550.0,2012.0,TRX520FW2M,Red,10-07-2021,101
4536,4537,NaN,611.0,2010.0,RMZ250,White,11/14/21,104
4537,4538,NaN,550.0,2019.0,CRF 100F,yellow,1/13/22,115
4538,4539,NaN,NaN,NaN,NaN,NaN,02-03-2022,102
4539,4540,NaN,NaN,NaN,NaN,NaN,10-09-2021,105
4540,4541,NaN,NaN,NaN,NaN,NaN,11/23/21,102
4541,4542,NaN,NaN,NaN,NaN,NaN,2/22/22,104
4542,4543,NaN,NaN,NaN,NaN,NaN,12/22/21,109
4543,4544,NaN,NaN,NaN,NaN,NaN,04-04-2022,103
4544,4545,NaN,NaN,NaN,NaN,NaN,04-04-2022,103
4545,4546,NaN,NaN,NaN,NaN,NaN,2/23/22,102
4546,4547,NaN,NaN,NaN,NaN,NaN,10/19/21,102
4547,4548,NaN,NaN,NaN,NaN,NaN,12/29/21,102
4548,4549,NaN,NaN,NaN,NaN,NaN,2/18/22,102
4549,4550,NaN,NaN,NaN,NaN,NaN,2/14/22,109
4550,4551,NaN,NaN,NaN,NaN,NaN,03-09-2022,102
4551,4552,NaN,NaN,NaN,NaN,NaN,03-07-2022,109
4552,4553,NaN,NaN,NaN,NaN,NaN,3/14/22,102

In [24]:
sv['vehicle_type'].unique()

array(['Trailer', 'Boat Trailer', 'Roadbike', 'Moped', 'Trailer - Heavy',
       'Caravan', 'Hatchback', 'Saloon', 'Stationwagon', 'Tractor',
       'Trail Bike', 'Light Van', 'All Terrain Vehicle', 'Utility',
       'Other Truck', 'Sports Car', 'Flat Deck Truck', 'Light Bus',
       'Mobile Home - Light', 'Convertible', 'Heavy Van',
       'Special Purpose Vehicle', 'Articulated Truck',
       'Cab and Chassis Only', 'Mobile Machine', nan], dtype=object)

In [25]:
sv=sv.dropna(subset=['make_id'])
sv.shape

(4538, 8)

In [26]:
sv[sv['vehicle_type'].isna()]

,vehicle_id,vehicle_type,make_id,model_year,vehicle_desc,color,date_stolen,location_id
4527,4528,NaN,505.0,2017.0,ETX 150,Black,12/13/21,104
4528,4529,NaN,507.0,2011.0,A8,Grey,12/14/21,102
4529,4530,NaN,512.0,2009.0,335i,Black,2/22/22,102
4530,4531,NaN,550.0,2009.0,TTR125,Blue,1/14/22,104
4531,4532,NaN,589.0,2021.0,NQI,whiTe,03-07-2022,102
4532,4533,NaN,611.0,2014.0,SWIFT,Red,11/17/21,108
4533,4534,NaN,611.0,2007.0,JIMNY,Black,01-11-2022,115
4534,4535,NaN,520.0,2005.0,30600,Yellow,11/23/21,102
4535,4536,NaN,550.0,2012.0,TRX520FW2M,Red,10-07-2021,101
4536,4537,NaN,611.0,2010.0,RMZ250,White,11/14/21,104
4537,4538,NaN,550.0,2019.0,CRF 100F,yellow,1/13/22,115

In [27]:
round(sv['vehicle_type'].value_counts(normalize=True,dropna=False)*100,2)

vehicle_type
Stationwagon               20.82
Saloon                     18.75
Hatchback                  14.19
Trailer                    12.83
Utility                    10.27
Roadbike                    6.54
Moped                       4.12
Light Van                   3.39
Boat Trailer                2.31
Trailer - Heavy             1.98
Caravan                     0.97
Other Truck                 0.93
Sports Car                  0.88
Flat Deck Truck             0.37
Mobile Home - Light         0.33
Convertible                 0.26
NaN                         0.24
Cab and Chassis Only        0.18
Heavy Van                   0.15
Light Bus                   0.13
All Terrain Vehicle         0.11
Tractor                     0.09
Trail Bike                  0.04
Mobile Machine              0.04
Special Purpose Vehicle     0.02
Articulated Truck           0.02
Name: proportion, dtype: float64

In [28]:
sv=sv.dropna(subset='vehicle_type')
sv.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4527 entries, 0 to 4526
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   vehicle_id    4527 non-null   int64
 1   vehicle_type  4527 non-null   object
 2   make_id       4527 non-null   float64
 3   model_year    4527 non-null   float64
 4   vehicle_desc  4509 non-null   object
 5   color         4527 non-null   object
 6   date_stolen   4527 non-null   object
 7   location_id   4527 non-null   int64
dtypes: float64(2), int64(2), object(4)
memory usage: 318.3+ KB

In [29]:
sv

,vehicle_id,vehicle_type,make_id,model_year,vehicle_desc,color,date_stolen,location_id
0,1,Trailer,623.0,2021.0,BST2021D,Silver,11-05-2021,102
1,2,Boat Trailer,623.0,2021.0,OUTBACK BOATS FT470,Silver,12/13/21,105
2,3,Boat Trailer,623.0,2021.0,ASD JETSKI,Silver,2/13/22,102
3,4,Trailer,623.0,2021.0,MSC 7X4,Silver,11/13/21,106
4,5,Trailer,623.0,2018.0,D-MAX 8X5,Silver,01-10-2022,102
...,...,...,...,...,...,...,...,...
4522,4523,Trailer,549.0,1993.0,NaN,Silver,12-12-2021,102
4523,4524,Trailer,549.0,1994.0,NaN,Grey,12/21/21,103
4524,4525,Trailer,623.0,1995.0,NaN,greeN,1/25/22,105
4525,4526,Trailer - Heavy,549.0,1990.0,NaN,Grey,04-02-2022,103
4526,4527,Stationwagon,555.0,1995.0,NaN,Red,01-04-2022,114

In [30]:
sv['color']=sv['color'].str.title()
sv.head(5)

,vehicle_id,vehicle_type,make_id,model_year,vehicle_desc,color,date_stolen,location_id
0,1,Trailer,623.0,2021.0,BST2021D,Silver,11-05-2021,102
1,2,Boat Trailer,623.0,2021.0,OUTBACK BOATS FT470,Silver,12/13/21,105
2,3,Boat Trailer,623.0,2021.0,ASD JETSKI,Silver,2/13/22,102
3,4,Trailer,623.0,2021.0,MSC 7X4,Silver,11/13/21,106
4,5,Trailer,623.0,2018.0,D-MAX 8X5,Silver,01-10-2022,102

In [31]:
sv.tail(5)

,vehicle_id,vehicle_type,make_id,model_year,vehicle_desc,color,date_stolen,location_id
4522,4523,Trailer,549.0,1993.0,NaN,Silver,12-12-2021,102
4523,4524,Trailer,549.0,1994.0,NaN,Grey,12/21/21,103
4524,4525,Trailer,623.0,1995.0,NaN,Green,1/25/22,105
4525,4526,Trailer - Heavy,549.0,1990.0,NaN,Grey,04-02-2022,103
4526,4527,Stationwagon,555.0,1995.0,NaN,Red,01-04-2022,114

In [32]:
sv

,vehicle_id,vehicle_type,make_id,model_year,vehicle_desc,color,date_stolen,location_id
0,1,Trailer,623.0,2021.0,BST2021D,Silver,11-05-2021,102
1,2,Boat Trailer,623.0,2021.0,OUTBACK BOATS FT470,Silver,12/13/21,105
2,3,Boat Trailer,623.0,2021.0,ASD JETSKI,Silver,2/13/22,102
3,4,Trailer,623.0,2021.0,MSC 7X4,Silver,11/13/21,106
4,5,Trailer,623.0,2018.0,D-MAX 8X5,Silver,01-10-2022,102
...,...,...,...,...,...,...,...,...
4522,4523,Trailer,549.0,1993.0,NaN,Silver,12-12-2021,102
4523,4524,Trailer,549.0,1994.0,NaN,Grey,12/21/21,103
4524,4525,Trailer,623.0,1995.0,NaN,Green,1/25/22,105
4525,4526,Trailer - Heavy,549.0,1990.0,NaN,Grey,04-02-2022,103
4526,4527,Stationwagon,555.0,1995.0,NaN,Red,01-04-2022,114

In [33]:
sv['date_stolen'] = pd.to_datetime(
    sv['date_stolen'],
    format='mixed',   
    errors='coerce'
)
sv

,vehicle_id,vehicle_type,make_id,model_year,vehicle_desc,color,date_stolen,location_id
0,1,Trailer,623.0,2021.0,BST2021D,Silver,2021-11-05,102
1,2,Boat Trailer,623.0,2021.0,OUTBACK BOATS FT470,Silver,2021-12-13,105
2,3,Boat Trailer,623.0,2021.0,ASD JETSKI,Silver,2022-02-13,102
3,4,Trailer,623.0,2021.0,MSC 7X4,Silver,2021-11-13,106
4,5,Trailer,623.0,2018.0,D-MAX 8X5,Silver,2022-01-10,102
...,...,...,...,...,...,...,...,...
4522,4523,Trailer,549.0,1993.0,NaN,Silver,2021-12-12,102
4523,4524,Trailer,549.0,1994.0,NaN,Grey,2021-12-21,103
4524,4525,Trailer,623.0,1995.0,NaN,Green,2022-01-25,105
4525,4526,Trailer - Heavy,549.0,1990.0,NaN,Grey,2022-04-02,103
4526,4527,Stationwagon,555.0,1995.0,NaN,Red,2022-01-04,114

In [34]:
sv['date_stolen'].isna().sum()

np.int64(0)

In [35]:
sv[['make_id','model_year']]=sv[['make_id','model_year']].astype(int)
sv

,vehicle_id,vehicle_type,make_id,model_year,vehicle_desc,color,date_stolen,location_id
0,1,Trailer,623,2021,BST2021D,Silver,2021-11-05,102
1,2,Boat Trailer,623,2021,OUTBACK BOATS FT470,Silver,2021-12-13,105
2,3,Boat Trailer,623,2021,ASD JETSKI,Silver,2022-02-13,102
3,4,Trailer,623,2021,MSC 7X4,Silver,2021-11-13,106
4,5,Trailer,623,2018,D-MAX 8X5,Silver,2022-01-10,102
...,...,...,...,...,...,...,...,...
4522,4523,Trailer,549,1993,NaN,Silver,2021-12-12,102
4523,4524,Trailer,549,1994,NaN,Grey,2021-12-21,103
4524,4525,Trailer,623,1995,NaN,Green,2022-01-25,105
4525,4526,Trailer - Heavy,549,1990,NaN,Grey,2022-04-02,103
4526,4527,Stationwagon,555,1995,NaN,Red,2022-01-04,114

In [36]:
col=sv.select_dtypes(include='object').columns.tolist()
for i in col:
    print(f'Column: {i}')
    print(sv[i].value_counts())
    print('-----------------------')

Column: vehicle_type
vehicle_type
Stationwagon               945
Saloon                     851
Hatchback                  644
Trailer                    582
Utility                    466
Roadbike                   297
Moped                      187
Light Van                  154
Boat Trailer               105
Trailer - Heavy             90
Caravan                     44
Other Truck                 42
Sports Car                  40
Flat Deck Truck             17
Mobile Home - Light         15
Convertible                 12
Cab and Chassis Only         8
Heavy Van                    7
Light Bus                    6
All Terrain Vehicle          5
Tractor                      4
Trail Bike                   2
Mobile Machine               2
Articulated Truck            1
Special Purpose Vehicle      1
Name: count, dtype: int64
-----------------------
Column: vehicle_desc
vehicle_desc
HILUX              137
COURIER            132
DEMIO               94
LEGACY              88
ATENZA              79
                  ...
KC95EXC              1
8X5 CONT TANDEM      1
TRAILPRO             1
MAINLINE 400         1
8X4 "6" TANDOM       1
Name: count, Length: 1169, dtype: int64
-----------------------
Column: color
color
Silver    1268
White      932
Black      586
Blue       511
Red        388
Grey       377
Green      224
Gold        77
Brown       49
Yellow      37
Orange      35
Purple      26
Cream        9
Silve        4
Pink         4
Name: count, dtype: int64
-----------------------

In [37]:
sv['color']=sv['color'].replace('Silve','Silver')
sv['color'].value_counts()

color
Silver    1272
White      932
Black      586
Blue       511
Red        388
Grey       377
Green      224
Gold        77
Brown       49
Yellow      37
Orange      35
Purple      26
Cream        9
Pink         4
Name: count, dtype: int64

### Cleaned Data

In [38]:
locn

    location_id              region      country  population  density
0           101           Northland  New Zealand      201500    16.11
1           102            Auckland  New Zealand     1695200   343.09
2           103             Waikato  New Zealand      513800    21.50
3           104       Bay of Plenty  New Zealand      347700    28.80
4           105            Gisborne  New Zealand       52100     6.21
5           106         Hawke's Bay  New Zealand      182700    12.92
6           107            Taranaki  New Zealand      127300    17.55
7           108  Manawatu-Whanganui  New Zealand      258200    11.62
8           109          Wellington  New Zealand      543500    67.52
9           110              Tasman  New Zealand       58700     6.10
10          111              Nelson  New Zealand       54500   129.15
11          112         Marlborough  New Zealand       51900     4.94
12          113          West Coast  New Zealand       32700     1.41
13          114          Canterbury  New Zealand      655000    14.72
14          115               Otago  New Zealand      246000     7.89
15          116           Southland  New Zealand      102400     3.28

In [39]:
vd

     make_id      make_name make_type
0        501  Aakron Xpress  Standard
1        502           Adly  Standard
2        503          Alpha  Standard
3        504          Anglo  Standard
4        505        Aprilia  Standard
..       ...            ...       ...
133      634          Volvo    Luxury
134      635        Voyager  Standard
135      636         Yamaha  Standard
136      637         Zephyr  Standard
137      638           Znen  Standard

[138 rows x 3 columns]

In [40]:
sv

,vehicle_id,vehicle_type,make_id,model_year,vehicle_desc,color,date_stolen,location_id
0,1,Trailer,623,2021,BST2021D,Silver,2021-11-05,102
1,2,Boat Trailer,623,2021,OUTBACK BOATS FT470,Silver,2021-12-13,105
2,3,Boat Trailer,623,2021,ASD JETSKI,Silver,2022-02-13,102
3,4,Trailer,623,2021,MSC 7X4,Silver,2021-11-13,106
4,5,Trailer,623,2018,D-MAX 8X5,Silver,2022-01-10,102
...,...,...,...,...,...,...,...,...
4522,4523,Trailer,549,1993,NaN,Silver,2021-12-12,102
4523,4524,Trailer,549,1994,NaN,Grey,2021-12-21,103
4524,4525,Trailer,623,1995,NaN,Green,2022-01-25,105
4525,4526,Trailer - Heavy,549,1990,NaN,Grey,2022-04-02,103
4526,4527,Stationwagon,555,1995,NaN,Red,2022-01-04,114

### Data Validation

In [48]:
sv[~sv['make_id'].isin(vd['make_id'])]

Empty DataFrame
Columns: [vehicle_id, vehicle_type, make_id, model_year, vehicle_desc, color, date_stolen, location_id]
Index: []

In [49]:
sv[~sv['location_id'].isin(locn['location_id'])]

Empty DataFrame
Columns: [vehicle_id, vehicle_type, make_id, model_year, vehicle_desc, color, date_stolen, location_id]
Index: []

In [41]:
locn.to_csv('locn.csv',index=False,sep=';', encoding='utf-8')
vd.to_csv('vd.csv',index=False,sep=';', encoding='utf-8')
sv.to_csv('sv.csv',index=False,date_format='%Y-%m-%d',sep=';', encoding='utf-8')